# Generated by Django 4.0.4 on 2022-05-27 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_profile', '0001_initial'),
        ('app_learning_space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('like_count', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_profile.profile')),
                ('learning_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_learning_space.learningspace')),
            ],
        ),
    ]
