# Generated by Django 4.0.4 on 2022-05-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_profile', '0002_alter_profile_profile_picture'),
        ('app_article', '0002_article_created_at_article_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_article.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_profile.profile')),
            ],
        ),
    ]
