# Generated by Django 4.0.4 on 2022-05-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning_space', '0004_alter_learningspace_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningspace',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
