# Generated by Django 4.0.4 on 2022-05-30 23:34

import app_learning_space.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning_space', '0005_alter_learningspace_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningspace',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=app_learning_space.models.get_upload_path),
        ),
    ]
